PROGRAM P1

IMPLICIT NONE

INTEGER :: N=3,M=2,P=2,RESULT=0
REAL :: INTEREST
CHARACTER *20::FIRST_NAME, FAMILY_NAME

PRINT *, 'ENTER YOUR NAME, LESS THAN 20 CHARACTER'
READ *, FIRST_NAME, FAMILY_NAME
PRINT *, 'HELLO ', FIRST_NAME, FAMILY_NAME
RESULT = N**(M**P)
PRINT *, 'THE RESULT IS ', RESULT
END PROGRAM P1
