PROGRAM Rainfall

IMPLICIT NONE

REAL :: TOTAL=0.0, AVERAGE=0.0
REAL, DIMENSION(1:12) :: R
INTEGER :: MONTH

        PRINT *, 'RAINFALL MEASURE EACH MONTH '
        DO MONTH=1,12
        READ *, R(MONTH)
        TOTAL=TOTAL+R(MONTH)
        ENDDO
        AVERAGE=TOTAL/12
        PRINT *, 'TOTAL RAINFALL THROUGHOUT THE YEAR '
        PRINT *, TOTAL
        PRINT *, 'AVERAGE VALUE OF RAINFALL THROUGHOUT THE YEAR IS '
        PRINT *, AVERAGE

END PROGRAM Rainfall
