PROGRAM FACTORIAL

IMPLICIT NONE

INTEGER :: N=1,FACT=1,M=1
REAL :: R=1
PRINT *,'ENTER THE NUMBER WHOSE FACTORIAL IS TO BE FOUND '
READ *, N
DO 17 N=1,N
        FACT=FACT*N
   17   CONTINUE
        PRINT *, 'THE FACTORIAL IS ', FACT
STOP
M=1/FACT
R=1/FACT
PRINT *, M
PRINT *, R
END PROGRAM FACTORIAL
